export const ar = {
  login: {
    title: 'تسجيل دخول الطاقم الطبي',
    mobileLabel: 'رقم الجوال',
    passwordLabel: 'كلمة المرور',
    submitButton: 'دخول',
    forgotPasswordLink: 'نسيت كلمة المرور؟',
  },
  forgotPassword: {
    title: 'استعادة كلمة المرور',
    mobileLabel: 'رقم الجوال',
    submitButton: 'إرسال رمز التحقق',
  },
  resetPassword: {
    title: 'إعادة تعيين كلمة المرور',
    codeLabel: 'رمز التحقق',
    newPasswordLabel: 'كلمة المرور الجديدة',
    submitButton: 'تعيين كلمة المرور',
  },
  changePassword: {
    title: 'يجب تغيير كلمة المرور',
    description: 'لأسباب أمنية، يجب عليك تعيين كلمة مرور جديدة قبل المتابعة',
    currentPasswordLabel: 'كلمة المرور الحالية',
    newPasswordLabel: 'كلمة المرور الجديدة',
    submitButton: 'تحديث كلمة المرور',
  },
  shell: {
    patientsLink: 'المرضى',
    reviewQueueLink: 'قائمة المراجعة',
    complaintsLink: 'الشكاوى',
    adminReportsLink: 'التقارير الإدارية',
    staffAccountsLink: 'حسابات الطاقم',
    myCliniciansLink: 'أخصائيو الإشراف',
    questionnairesLink: 'الاستبيانات',
    logoutButton: 'تسجيل الخروج',
    roles: {
      CLINICIAN: 'أخصائي',
      SUPERVISOR: 'مشرف',
      ADMIN: 'مدير النظام',
    },
  },
  patients: {
    title: 'بحث عن المرضى',
    searchPlaceholder: 'ابحث بالاسم أو رقم الهوية',
    searchButton: 'بحث',
    tableName: 'الاسم',
    tableNationalId: 'رقم الهوية',
    tableGender: 'الجنس',
    tableDateOfBirth: 'تاريخ الميلاد',
    tableStatus: 'الحالة',
    genders: { MALE: 'ذكر', FEMALE: 'أنثى' } as Record<string, string>,
    statuses: { ACTIVE: 'نشط', DISABLED: 'معطل' } as Record<string, string>,
    noResults: 'لا توجد نتائج',
    emptyState: 'ابحث عن مريض بالاسم أو رقم الهوية',
  },
  reviewQueue: {
    title: 'قائمة المراجعة',
    emptyState: 'لا توجد عينات بانتظار المراجعة',
    patientNameLabel: 'المريض',
    submittedAtLabel: 'تاريخ الإرسال',
    escalatedLabel: 'مصعّدة',
    reserveButton: 'حجز للمراجعة',
  },
  patientDetail: {
    loadError: 'تعذر تحميل بيانات المريض',
    profileTitle: 'الملف الشخصي',
    fullNameLabel: 'الاسم الكامل',
    nationalIdLabel: 'رقم الهوية',
    addressLabel: 'العنوان',
    referralSourceLabel: 'مصدر الإحالة',
    initialDiagnosisLabel: 'التشخيص الأولي',
    medicalHistoryLabel: 'التاريخ المرضي',
    medicationsLabel: 'الأدوية',
    allergiesLabel: 'الحساسية',
    familyHistoryLabel: 'التاريخ العائلي',
    editButton: 'تعديل',
    saveButton: 'حفظ',
    cancelButton: 'إلغاء',
    disableButton: 'تعطيل الحساب',
    enableButton: 'تفعيل الحساب',
    linkGuardianTitle: 'ربط ولي أمر',
    guardianMobileLabel: 'رقم جوال ولي الأمر',
    linkGuardianButton: 'ربط',
    assessmentsTitle: 'التقييمات',
    noAssessments: 'لا توجد تقييمات بعد',
    assessmentTypeLabel: 'النوع',
    assessmentStatusLabel: 'الحالة',
    assessmentDateLabel: 'التاريخ',
    assessmentTypes: { INITIAL: 'أولي', PERIODIC: 'دوري', FINAL: 'نهائي' } as Record<string, string>,
    assessmentStatuses: { DRAFT: 'مسودة', APPROVED: 'معتمد' } as Record<string, string>,
    newAssessmentButton: 'تقييم جديد',
    difficultSituationsLabel: 'المواقف الصعبة',
    anxietyLevelLabel: 'مستوى القلق',
    initialGoalsLabel: 'الأهداف الأولية',
    clinicianNotesLabel: 'ملاحظات الأخصائي',
    ssi4FrequencyLabel: 'SSI-4: التكرار',
    ssi4DurationLabel: 'SSI-4: المدة',
    ssi4PhysicalConcomitantsLabel: 'SSI-4: الأعراض الجسدية المصاحبة',
    ssi4TotalLabel: 'SSI-4: المجموع',
    approveButton: 'اعتماد',
    severityCategoryLabel: 'درجة الشدة',
    severityCategories: {
      MILD: 'خفيفة',
      MODERATE: 'متوسطة',
      SEVERE: 'شديدة',
      VERY_SEVERE: 'شديدة جدًا',
    } as Record<string, string>,
    baselineComparisonButton: 'مقارنة بالتقييم الأساسي',
    baselineComparisonTitle: 'مقارنة بالتقييم الأساسي',
    noBaselineYet: 'لا تتوفر بيانات كافية للمقارنة',
    treatmentPlanTitle: 'الخطة العلاجية',
    goalsLabel: 'الأهداف',
    phaseLabel: 'المرحلة',
    phases: {
      PHASE_1: 'المرحلة الأولى',
      PHASE_2: 'المرحلة الثانية',
      PHASE_3: 'المرحلة الثالثة',
      PHASE_4: 'المرحلة الرابعة',
      PHASE_5: 'المرحلة الخامسة',
    } as Record<string, string>,
    reviewDateLabel: 'تاريخ المراجعة',
    linkedExercisesTitle: 'التمارين المرتبطة',
    noLinkedExercises: 'لا توجد تمارين مرتبطة',
    exerciseTitleLabel: 'التمرين',
    frequencyLabel: 'التكرار الأسبوعي',
    sequenceLabel: 'الترتيب',
    removeExerciseButton: 'إزالة',
    addExerciseButton: 'إضافة',
    transitionToPhaseLabel: 'الانتقال إلى مرحلة',
    rationaleLabel: 'السبب',
    transitionButton: 'تنفيذ الانتقال',
    noActivePlan: 'لا توجد خطة علاجية نشطة',
    newPlanTitle: 'خطة علاجية جديدة',
    assessmentLabel: 'التقييم المعتمد',
    createPlanButton: 'إنشاء خطة',
    pastPlansTitle: 'الخطط السابقة',
  },
  sampleReview: {
    title: 'مراجعة العينة',
    reservedByOtherLabel: 'محجوزة لأخصائي آخر',
    notYetReservedLabel: 'لم تُحجز بعد للمراجعة',
    selfReportTitle: 'التقييم الذاتي للمستفيد',
    selfSeverityCurrentLabel: 'شدة التلعثم الحالية',
    selfSeverityExpectedNextLabel: 'الشدة المتوقعة للمستوى التالي',
    camperdownPerformanceLabel: 'تقييم الأداء (Camperdown)',
    clientOpinionLabel: 'رأي المستفيد في أدائه',
    partsTitle: 'أجزاء العينة',
    playButton: 'تشغيل',
    loadingMedia: 'جارٍ تحميل التسجيل...',
    mediaError: 'تعذر تحميل التسجيل',
    interventionTitle: 'التدخل المباشر',
    interventionTypeLabel: 'نوع التدخل',
    interventionTypes: {
      VIDEO_MEETING: 'لقاء مرئي',
      VOICE_CONSULTATION: 'استشارة صوتية',
      TARGETED_MESSAGE: 'رسالة موجهة',
      CLINICAL_ACTION: 'إجراء سريري',
    } as Record<string, string>,
    interventionReasonLabel: 'سبب التدخل',
    requestInterventionButton: 'طلب تدخل مباشر',
    interventionOutcomeLabel: 'نتيجة التدخل',
    completeInterventionButton: 'إنهاء التدخل',
    decisionTitle: 'قرار المراجعة',
    decisionLabel: 'القرار',
    decisions: {
      TRANSITION: 'الانتقال إلى المستوى التالي',
      LEVEL_REPEAT: 'إعادة المستوى الحالي',
      TECHNICAL_RERECORD: 'طلب إعادة تسجيل أجزاء تقنيًا',
    } as Record<string, string>,
    clinicianOpinionScoreLabel: 'تقييم الأخصائي (1-9)',
    reviewNotesLabel: 'ملاحظات المراجعة',
    damagedPartsLabel: 'الأجزاء التي تحتاج إعادة تسجيل',
    submitDecisionButton: 'إرسال القرار',
    transferTitle: 'نقل مسؤولية المراجعة',
    transferToLabel: 'نقل إلى',
    transferReasonLabel: 'سبب النقل',
    transferButton: 'تنفيذ النقل',
    noClinicians: 'لا يوجد أخصائيون تحت إشرافك',
  },
  progress: {
    title: 'التقدم',
    currentLevelLabel: 'المستوى الحالي',
    levelsCompletedLabel: 'المستويات المكتملة',
    totalTrainingEventsLabel: 'إجمالي التدريبات',
    daysInProgramLabel: 'عدد أيام البرنامج',
    repeatedLevelsLabel: 'المستويات المعادة',
    noRepeatedLevels: 'لا يوجد',
    passedLevelsTitle: 'المستويات المجتازة',
    noPassedLevels: 'لم يُجتز أي مستوى بعد',
    levelNameLabel: 'المستوى',
    levelOrderLabel: 'الترتيب',
    passedAtLabel: 'تاريخ الاجتياز',
    notPassedYet: '—',
  },
  reports: {
    patientSectionTitle: 'التقارير',
    assessmentResultsTitle: 'نتائج التقييمات',
    noAssessmentResults: 'لا توجد نتائج تقييمات',
    assessmentTypeLabel: 'النوع',
    assessmentStatusLabel: 'الحالة',
    ssi4TotalLabel: 'مجموع SSI-4',
    severityCategoryLabel: 'درجة الشدة',
    approvedAtLabel: 'تاريخ الاعتماد',
    medicalReportTitle: 'التقرير الطبي',
    noClinicalInfo: 'لا توجد معلومات سريرية',
    referralReasonLabel: 'سبب الإحالة',
    initialDiagnosisLabel: 'التشخيص الأولي',
    medicalHistoryLabel: 'التاريخ المرضي',
    medicationsLabel: 'الأدوية',
    allergiesLabel: 'الحساسية',
    familyHistoryLabel: 'التاريخ العائلي',
    latestAssessmentTitle: 'آخر تقييم معتمد',
    noLatestAssessment: 'لا يوجد تقييم معتمد',
    activePlanTitle: 'الخطة العلاجية النشطة',
    noActivePlanForReport: 'لا توجد خطة علاجية نشطة',
    exportMedicalPdfButton: 'تصدير التقرير الطبي (PDF)',
    reportGeneratedAtLabel: 'تاريخ إصدار التقرير',
    reportFooterNote: 'تقرير مُولَّد آليًا من منصة كلامي',
    adminReportsTitle: 'التقارير الإدارية',
    tabs: {
      kpiDashboard: 'المؤشرات',
      operationalStatus: 'الحالة التشغيلية',
      registeredUsers: 'المستخدمون المسجلون',
      serviceModifications: 'سجل التعديلات',
      staffPerformance: 'أداء الطاقم',
      complaintsReport: 'تقرير الشكاوى',
    },
    kpi: {
      totalPatients: 'إجمالي المرضى النشطين',
      totalRegisteredUsers: 'إجمالي المستخدمين',
      newRegistrationsLast30Days: 'تسجيلات آخر 30 يومًا',
      approvedDiagnosesCount: 'التشخيصات المعتمدة',
      activeCases: 'الحالات النشطة',
      inactiveCases: 'الحالات المتوقفة',
      levelTransitions: 'انتقالات المستويات',
      severityTitle: 'التقييمات حسب درجة الشدة',
      consultationsTitle: 'الاستشارات حسب الحالة',
      revenueNote: 'الإيرادات غير متاحة (وحدة المدفوعات مؤجَّلة للمرحلة الثانية)',
    },
    usersByRoleTitle: 'المستخدمون حسب الدور',
    patientProfilesByStatusTitle: 'ملفات المرضى حسب الحالة',
    treatmentPlansByStatusTitle: 'الخطط العلاجية حسب الحالة',
    trainingCyclesByStatusTitle: 'دورات التدريب حسب الحالة',
    noData: 'لا توجد بيانات',
    roles: {
      PATIENT: 'مستفيد',
      CAREGIVER: 'ولي أمر',
      CLINICIAN: 'أخصائي',
      SUPERVISOR: 'مشرف',
      ADMIN: 'مدير النظام',
    } as Record<string, string>,
    planStatuses: { ACTIVE: 'نشطة', INACTIVE: 'غير نشطة' } as Record<string, string>,
    userStatuses: {
      PENDING_VERIFICATION: 'بانتظار التحقق',
      ACTIVE: 'نشط',
      LOCKED: 'مقفل',
      DISABLED: 'معطل',
    } as Record<string, string>,
    cycleStatuses: {
      ACTIVE_LEVEL_TRAINING: 'تدريب المستوى النشط',
      SAMPLE_ELIGIBLE: 'مؤهل لتسجيل عينة',
      SAMPLE_PREPARATION: 'تحضير العينة',
      SAMPLE_SUBMISSION_DELAYED: 'تأخر إرسال العينة',
      SAMPLE_SUBMITTED: 'تم إرسال العينة',
      WAITING_FOR_SPECIALIST: 'بانتظار الأخصائي',
      UNDER_REVIEW: 'قيد المراجعة',
      DIRECT_INTERVENTION_REQUIRED: 'يتطلب تدخلًا مباشرًا',
      WAITING_FINAL_DECISION_AFTER_INTERVENTION: 'بانتظار القرار النهائي بعد التدخل',
      TECHNICAL_PARTIAL_RERECORD: 'إعادة تسجيل جزئي (فني)',
      LEVEL_REPEAT_DECIDED: 'تقرر إعادة المستوى',
      NEXT_LEVEL_APPROVED: 'تم اعتماد المستوى التالي',
      CLOSED_DUE_TO_INACTIVITY: 'أُغلقت بسبب عدم النشاط',
      SUBSCRIPTION_EXPIRED_CLINICAL_FLOW_OPEN: 'انتهى الاشتراك (المسار السريري مفتوح)',
    } as Record<string, string>,
    fullNameLabel: 'الاسم الكامل',
    mobileLabel: 'رقم الجوال',
    roleLabel: 'الدور',
    statusLabel: 'الحالة',
    caseProgressLabel: 'حالة التقدم',
    fromDateLabel: 'من تاريخ',
    toDateLabel: 'إلى تاريخ',
    actionLabel: 'الإجراء',
    entityLabel: 'الكيان',
    actorLabel: 'المستخدم',
    dateLabel: 'التاريخ',
    noServiceModifications: 'لا توجد تعديلات في هذه الفترة',
    patientsHandledLabel: 'عدد المرضى',
    reviewsApprovedLabel: 'المراجعات المعتمدة',
    reviewsRepeatRequiredLabel: 'مراجعات تتطلب إعادة',
    complaintsAgainstLabel: 'الشكاوى المقدمة ضده',
    noStaffPerformance: 'لا توجد بيانات أداء',
    noRegisteredUsers: 'لا يوجد مستخدمون',
  },
  complaints: {
    title: 'الشكاوى',
    emptyState: 'لا توجد شكاوى',
    typeLabel: 'النوع',
    types: { COMPLAINT: 'شكوى', SUGGESTION: 'اقتراح' } as Record<string, string>,
    subjectLabel: 'الموضوع',
    descriptionLabel: 'الوصف',
    statusLabel: 'الحالة',
    statuses: { OPEN: 'مفتوحة', REVIEWED: 'تمت مراجعتها', RESOLVED: 'تم حلها' } as Record<string, string>,
    createdAtLabel: 'تاريخ التقديم',
    statusFilterLabel: 'تصفية حسب الحالة',
    statusFilterAll: 'الكل',
  },
  staffAccounts: {
    title: 'حسابات الطاقم',
    newAccountTitle: 'حساب جديد',
    fullNameLabel: 'الاسم الكامل',
    mobileLabel: 'رقم الجوال',
    emailLabel: 'البريد الإلكتروني',
    passwordLabel: 'كلمة المرور',
    roleLabel: 'الدور',
    createButton: 'إنشاء الحساب',
    filterRoleLabel: 'تصفية حسب الدور',
    filterStatusLabel: 'تصفية حسب الحالة',
    filterAll: 'الكل',
    tableName: 'الاسم',
    tableMobile: 'رقم الجوال',
    tableEmail: 'البريد الإلكتروني',
    tableRole: 'الدور',
    tableStatus: 'الحالة',
    tableCreatedAt: 'تاريخ الإنشاء',
    disableButton: 'تعطيل',
    enableButton: 'تفعيل',
    noAccounts: 'لا توجد حسابات',
    assignSupervisorLabel: 'تعيين مشرف',
    noSupervisorOption: 'بدون مشرف',
    choosePlaceholder: 'اختر مشرفًا',
    assignSuccessMessage: 'تم التعيين',
  },
  myClinicians: {
    title: 'الأخصائيون الخاضعون لإشرافي',
    emptyState: 'لا يوجد أخصائيون معينون لك حاليًا',
    tableName: 'الاسم',
    tableMobile: 'رقم الجوال',
    tableStatus: 'الحالة',
  },
  errors: {
    unexpected: 'حدث خطأ غير متوقع',
  },
  consultation: {
    sectionTitle: 'الاستشارة المجانية',
    noConsultations: 'لا توجد طلبات استشارة',
    typeLabel: 'النوع',
    statusLabel: 'الحالة',
    reasonLabel: 'السبب',
    types: {
      VIDEO: 'مرئية',
      VOICE: 'صوتية',
    },
    statuses: {
      REQUESTED: 'تم الطلب',
      SCHEDULING: 'قيد الجدولة',
      SCHEDULED: 'مجدولة',
      COMPLETED: 'تم الاكتمال',
      CANCELLED: 'ملغاة',
    },
    statusSelectLabel: 'تحديث الحالة',
    scheduledAtLabel: 'موعد الاستشارة',
    meetingLinkLabel: 'رابط الاجتماع',
    outcomeNotesLabel: 'ملاحظات النتيجة',
    saveButton: 'حفظ',
    availabilityTitle: 'مواعيدي المتاحة للاستشارة',
    addSlotLabel: 'إضافة موعد متاح',
    publishSlotButton: 'نشر الموعد',
    noSlots: 'لم تنشر أي مواعيد بعد',
    slotStatuses: {
      AVAILABLE: 'متاح',
      BOOKED: 'محجوز',
    },
  },
  messages: {
    sectionTitle: 'المحادثة مع المريض',
    empty: 'لا توجد رسائل بعد',
    inputLabel: 'اكتب رسالة',
    sendButton: 'إرسال',
    fromMe: 'أنا',
    fromPatient: 'المريض',
    readLabel: 'تم الاطلاع',
  },
  questionnaires: {
    pageTitle: 'الاستبيانات المُهيكلة',
    createTitle: 'إنشاء استبيان جديد',
    titleLabel: 'عنوان الاستبيان',
    descriptionLabel: 'وصف (اختياري)',
    questionsLabel: 'الأسئلة',
    questionTextLabel: 'نص السؤال',
    questionTypeLabel: 'نوع السؤال',
    optionsLabel: 'الخيارات (افصل بينها بفاصلة)',
    requiredLabel: 'إلزامي',
    addQuestionButton: 'إضافة سؤال',
    removeQuestionButton: 'حذف',
    createButton: 'حفظ الاستبيان',
    existingTitle: 'الاستبيانات الحالية',
    noTemplates: 'لا توجد استبيانات بعد',
    activate: 'تفعيل',
    deactivate: 'إلغاء التفعيل',
    activeBadge: 'مُفعّل',
    inactiveBadge: 'غير مُفعّل',
    questionCount: 'عدد الأسئلة',
    types: {
      TEXT: 'نص حر',
      SINGLE_CHOICE: 'اختيار واحد',
      MULTI_CHOICE: 'اختيار متعدد',
      SCALE: 'مقياس رقمي',
    },
    responsesTitle: 'إجابات الاستبيانات',
    noResponses: 'لا توجد إجابات بعد',
    submittedAtLabel: 'تاريخ التعبئة',
  },
};
