export const ar = {
  login: {
    title: 'تسجيل دخول الطاقم الطبي',
    mobileLabel: 'رقم الجوال',
    passwordLabel: 'كلمة المرور',
    submitButton: 'دخول',
    forgotPasswordLink: 'نسيت كلمة المرور؟',
  },
  forgotPassword: {
    title: 'استعادة كلمة المرور',
    mobileLabel: 'رقم الجوال',
    submitButton: 'إرسال رمز التحقق',
  },
  resetPassword: {
    title: 'إعادة تعيين كلمة المرور',
    codeLabel: 'رمز التحقق',
    newPasswordLabel: 'كلمة المرور الجديدة',
    submitButton: 'تعيين كلمة المرور',
  },
  changePassword: {
    title: 'يجب تغيير كلمة المرور',
    description: 'لأسباب أمنية، يجب عليك تعيين كلمة مرور جديدة قبل المتابعة',
    currentPasswordLabel: 'كلمة المرور الحالية',
    newPasswordLabel: 'كلمة المرور الجديدة',
    submitButton: 'تحديث كلمة المرور',
  },
  shell: {
    patientsLink: 'المرضى',
    logoutButton: 'تسجيل الخروج',
    roles: {
      CLINICIAN: 'أخصائي',
      SUPERVISOR: 'مشرف',
      ADMIN: 'مدير النظام',
    },
  },
  patients: {
    title: 'بحث عن المرضى',
    searchPlaceholder: 'ابحث بالاسم أو رقم الهوية',
    searchButton: 'بحث',
    tableName: 'الاسم',
    tableNationalId: 'رقم الهوية',
    tableGender: 'الجنس',
    tableDateOfBirth: 'تاريخ الميلاد',
    tableStatus: 'الحالة',
    genders: { MALE: 'ذكر', FEMALE: 'أنثى' } as Record<string, string>,
    statuses: { ACTIVE: 'نشط', DISABLED: 'معطل' } as Record<string, string>,
    noResults: 'لا توجد نتائج',
    emptyState: 'ابحث عن مريض بالاسم أو رقم الهوية',
  },
  patientDetail: {
    loadError: 'تعذر تحميل بيانات المريض',
    profileTitle: 'الملف الشخصي',
    fullNameLabel: 'الاسم الكامل',
    nationalIdLabel: 'رقم الهوية',
    addressLabel: 'العنوان',
    referralSourceLabel: 'مصدر الإحالة',
    initialDiagnosisLabel: 'التشخيص الأولي',
    medicalHistoryLabel: 'التاريخ المرضي',
    medicationsLabel: 'الأدوية',
    allergiesLabel: 'الحساسية',
    familyHistoryLabel: 'التاريخ العائلي',
    editButton: 'تعديل',
    saveButton: 'حفظ',
    cancelButton: 'إلغاء',
    disableButton: 'تعطيل الحساب',
    enableButton: 'تفعيل الحساب',
    linkGuardianTitle: 'ربط ولي أمر',
    guardianMobileLabel: 'رقم جوال ولي الأمر',
    linkGuardianButton: 'ربط',
    assessmentsTitle: 'التقييمات',
    noAssessments: 'لا توجد تقييمات بعد',
    assessmentTypeLabel: 'النوع',
    assessmentStatusLabel: 'الحالة',
    assessmentDateLabel: 'التاريخ',
    assessmentTypes: { INITIAL: 'أولي', PERIODIC: 'دوري', FINAL: 'نهائي' } as Record<string, string>,
    assessmentStatuses: { DRAFT: 'مسودة', APPROVED: 'معتمد' } as Record<string, string>,
    newAssessmentButton: 'تقييم جديد',
    difficultSituationsLabel: 'المواقف الصعبة',
    anxietyLevelLabel: 'مستوى القلق',
    initialGoalsLabel: 'الأهداف الأولية',
    clinicianNotesLabel: 'ملاحظات الأخصائي',
    ssi4FrequencyLabel: 'SSI-4: التكرار',
    ssi4DurationLabel: 'SSI-4: المدة',
    ssi4PhysicalConcomitantsLabel: 'SSI-4: الأعراض الجسدية المصاحبة',
    ssi4TotalLabel: 'SSI-4: المجموع',
    approveButton: 'اعتماد',
    severityCategoryLabel: 'درجة الشدة',
    severityCategories: {
      MILD: 'خفيفة',
      MODERATE: 'متوسطة',
      SEVERE: 'شديدة',
      VERY_SEVERE: 'شديدة جدًا',
    } as Record<string, string>,
    baselineComparisonButton: 'مقارنة بالتقييم الأساسي',
    baselineComparisonTitle: 'مقارنة بالتقييم الأساسي',
    noBaselineYet: 'لا تتوفر بيانات كافية للمقارنة',
  },
  errors: {
    unexpected: 'حدث خطأ غير متوقع',
  },
};
