export const ar = {
  welcome: {
    title: 'أهلاً بك في كلامي',
    subtitle: 'رحلتك نحو طلاقة أفضل تبدأ هنا',
    registerCta: 'إنشاء حساب جديد',
    loginCta: 'لدي حساب بالفعل',
  },
  registerChoice: {
    title: 'لمن هذا الحساب؟',
    forSelf: 'أسجّل لنفسي',
    forChild: 'أسجّل لابني/ابنتي',
  },
  registerForm: {
    title: 'بيانات التسجيل',
    fullName: 'الاسم الكامل',
    mobile: 'رقم الجوال',
    email: 'البريد الإلكتروني (اختياري)',
    password: 'كلمة السر',
    submit: 'إرسال',
    mobileInvalid: 'رقم جوال غير صحيح',
    passwordTooShort: 'كلمة السر يجب ألا تقل عن 8 أحرف',
    nameRequired: 'الاسم مطلوب',
  },
  verify: {
    title: 'تأكيد رقم الجوال',
    subtitle: 'أدخل رمز التحقق',
    devModeLabel: 'وضع التطوير — الرمز:',
    submit: 'تأكيد',
    reasons: {
      NOT_FOUND: 'لا يوجد رمز نشط، يرجى طلب رمز جديد',
      EXPIRED: 'انتهت صلاحية الرمز (5 دقائق)، يرجى طلب رمز جديد',
      TOO_MANY_ATTEMPTS: 'تجاوزت عدد المحاولات المسموح، يرجى المحاولة لاحقًا',
      INCORRECT_CODE: 'الرمز غير صحيح، حاول مرة أخرى',
    },
  },
  login: {
    title: 'تسجيل الدخول',
    mobile: 'رقم الجوال',
    password: 'كلمة السر',
    submit: 'دخول',
    forgotPassword: 'نسيت كلمة السر؟',
    locked: 'الحساب مقفل مؤقتًا بسبب محاولات فاشلة متكررة، حاول بعد 15 دقيقة',
  },
  forgotPassword: {
    title: 'استعادة كلمة السر',
    mobile: 'رقم الجوال',
    submit: 'إرسال رمز الاستعادة',
  },
  resetPassword: {
    title: 'كلمة سر جديدة',
    code: 'رمز التحقق',
    newPassword: 'كلمة السر الجديدة',
    submit: 'حفظ',
  },
  program: {
    loading: 'جارٍ التحميل...',
    startProgram: 'ابدأ برنامجي',
    noTreatmentPlanYet: 'لم يُكمل فريقك الطبي خطة علاجك بعد — يرجى التواصل مع عيادتك',
    watchLevelContent: 'شاهد محتوى المستوى',
    logTraining: 'سجّل تدريب اليوم',
    sampleComingSoon: 'هذه المرحلة تتطلب تسجيل عينة صوتية — هذه الميزة قادمة في تحديث لاحق',
    waitingForSpecialist: 'بانتظار مراجعة أخصائيك لعينتك',
    pausedForInactivity: 'توقف برنامجك بسبب عدم النشاط — تواصل مع عيادتك لاستئنافه',
    genericWaiting: 'أخصائيك يراجع حالتك',
    therapistMessageBanner: 'لديك رسالة من أخصائيك',
    viewHistory: 'السجل',
    viewLevelContent: 'محتوى المستوى',
    logout: 'تسجيل الخروج',
  },
  levelContent: {
    title: 'محتوى المستوى',
    reflectionPrompt: 'فكّر في',
    trainingListTitle: 'قائمة التدريب',
    markWatched: 'وضع علامة كمشاهد',
  },
  history: {
    title: 'السجل',
    empty: 'لا يوجد سجل بعد',
    decisionLinePrefix: 'قرر الأخصائي:',
    decisions: {
      TRANSITION: 'الانتقال للمستوى التالي',
      LEVEL_REPEAT: 'إعادة هذا المستوى',
    },
  },
  sampleResult: {
    title: 'نتيجة عينتك',
    decisions: {
      TRANSITION: 'الانتقال للمستوى التالي',
      LEVEL_REPEAT: 'إعادة هذا المستوى',
    },
    clinicianNotesTitle: 'ملاحظات أخصائيك',
    selfReportTitle: 'تقييمك الذاتي',
    notFound: 'تعذر العثور على هذه النتيجة',
  },
  sampleRecording: {
    title: 'تسجيل عينتك الصوتية',
    record: 'ابدأ التسجيل',
    stopRecording: 'إيقاف التسجيل',
    play: 'تشغيل',
    pause: 'إيقاف مؤقت',
    micPermissionDenied: 'يلزم الوصول إلى الميكروفون لتسجيل عينتك',
    maxDurationReached: 'تم بلوغ الحد الأقصى لمدة التسجيل (3 دقائق)',
    secondsUnit: 'ث',
    requiredPartsTitle: 'الأجزاء المطلوبة',
    attemptsTitle: 'محاولاتك المسجّلة',
    attemptLabel: 'محاولة',
    deleteAttempt: 'حذف',
    maxAttemptsReached: 'وصلت للحد الأقصى (10 محاولات)',
    uploading: 'جارٍ الرفع...',
    next: 'التالي',
    back: 'رجوع',
    assignPartsTitle: 'اختر التسجيل المناسب لكل جزء',
    selfReportTitle: 'تقييمك الذاتي',
    selfSeverityCurrentLabel: 'شدة التلعثم الحالية',
    selfSeverityExpectedNextLabel: 'الشدة المتوقعة للمستوى التالي',
    camperdownPerformanceLabel: 'تقييم أدائك',
    clientOpinionLabel: 'رأيك في أدائك',
    submit: 'إرسال العينة',
  },
};
