export const ar = {
  welcome: {
    title: 'أهلاً بك في كلامي',
    subtitle: 'رحلتك نحو طلاقة أفضل تبدأ هنا',
    registerCta: 'إنشاء حساب جديد',
    loginCta: 'لدي حساب بالفعل',
  },
  registerChoice: {
    title: 'لمن هذا الحساب؟',
    forSelf: 'أسجّل لنفسي',
    forChild: 'أسجّل لابني/ابنتي',
  },
  registerForm: {
    title: 'بيانات التسجيل',
    fullName: 'الاسم الكامل',
    mobile: 'رقم الجوال',
    email: 'البريد الإلكتروني (اختياري)',
    password: 'كلمة السر',
    submit: 'إرسال',
    mobileInvalid: 'رقم جوال غير صحيح',
    passwordTooShort: 'كلمة السر يجب ألا تقل عن 8 أحرف',
    nameRequired: 'الاسم مطلوب',
  },
  verify: {
    title: 'تأكيد رقم الجوال',
    subtitle: 'أدخل رمز التحقق',
    devModeLabel: 'وضع التطوير — الرمز:',
    submit: 'تأكيد',
    reasons: {
      NOT_FOUND: 'لا يوجد رمز نشط، يرجى طلب رمز جديد',
      EXPIRED: 'انتهت صلاحية الرمز (5 دقائق)، يرجى طلب رمز جديد',
      TOO_MANY_ATTEMPTS: 'تجاوزت عدد المحاولات المسموح، يرجى المحاولة لاحقًا',
      INCORRECT_CODE: 'الرمز غير صحيح، حاول مرة أخرى',
    },
  },
  login: {
    title: 'تسجيل الدخول',
    mobile: 'رقم الجوال',
    password: 'كلمة السر',
    submit: 'دخول',
    forgotPassword: 'نسيت كلمة السر؟',
    locked: 'الحساب مقفل مؤقتًا بسبب محاولات فاشلة متكررة، حاول بعد 15 دقيقة',
  },
  forgotPassword: {
    title: 'استعادة كلمة السر',
    mobile: 'رقم الجوال',
    submit: 'إرسال رمز الاستعادة',
  },
  resetPassword: {
    title: 'كلمة سر جديدة',
    code: 'رمز التحقق',
    newPassword: 'كلمة السر الجديدة',
    submit: 'حفظ',
  },
  program: {
    loading: 'جارٍ التحميل...',
    startProgram: 'ابدأ برنامجي',
    noTreatmentPlanYet: 'لم يُكمل فريقك الطبي خطة علاجك بعد — يرجى التواصل مع عيادتك',
    watchLevelContent: 'شاهد محتوى المستوى',
    logTraining: 'سجّل تدريب اليوم',
    recordSample: 'سجّل عينتك',
    rerecordParts: 'أعد تسجيل الأجزاء المطلوبة',
    waitingForSpecialist: 'بانتظار مراجعة أخصائيك لعينتك',
    pausedForInactivity: 'توقف برنامجك بسبب عدم النشاط — تواصل مع عيادتك لاستئنافه',
    genericWaiting: 'أخصائيك يراجع حالتك',
    therapistMessageBanner: 'لديك رسالة من أخصائيك',
    viewHistory: 'السجل',
    viewLevelContent: 'محتوى المستوى',
    viewReports: 'التقارير',
    viewComplaints: 'الشكاوى',
    viewNotifications: 'الإشعارات',
    logout: 'تسجيل الخروج',
  },
  levelContent: {
    title: 'محتوى المستوى',
    reflectionPrompt: 'فكّر في',
    trainingListTitle: 'قائمة التدريب',
    markWatched: 'وضع علامة كمشاهد',
  },
  history: {
    title: 'السجل',
    empty: 'لا يوجد سجل بعد',
    decisionLinePrefix: 'قرر الأخصائي:',
    decisions: {
      TRANSITION: 'الانتقال للمستوى التالي',
      LEVEL_REPEAT: 'إعادة هذا المستوى',
    },
  },
  sampleResult: {
    title: 'نتيجة عينتك',
    decisions: {
      TRANSITION: 'الانتقال للمستوى التالي',
      LEVEL_REPEAT: 'إعادة هذا المستوى',
    },
    clinicianNotesTitle: 'ملاحظات أخصائيك',
    selfReportTitle: 'تقييمك الذاتي',
    notFound: 'تعذر العثور على هذه النتيجة',
  },
  sampleRecording: {
    title: 'تسجيل عينتك الصوتية',
    record: 'ابدأ التسجيل',
    stopRecording: 'إيقاف التسجيل',
    play: 'تشغيل',
    pause: 'إيقاف مؤقت',
    micPermissionDenied: 'يلزم الوصول إلى الميكروفون لتسجيل عينتك',
    cameraPermissionDenied: 'يلزم الوصول إلى الكاميرا والميكروفون لتسجيل عينتك',
    enableCamera: 'تفعيل الكاميرا',
    maxDurationReached: 'تم بلوغ الحد الأقصى لمدة التسجيل (3 دقائق)',
    secondsUnit: 'ث',
    requiredPartsTitle: 'الأجزاء المطلوبة',
    attemptsTitle: 'محاولاتك المسجّلة',
    attemptLabel: 'محاولة',
    deleteAttempt: 'حذف',
    maxAttemptsReached: 'وصلت للحد الأقصى (10 محاولات)',
    uploading: 'جارٍ الرفع...',
    next: 'التالي',
    back: 'رجوع',
    assignPartsTitle: 'اختر التسجيل المناسب لكل جزء',
    selfReportTitle: 'تقييمك الذاتي',
    selfSeverityCurrentLabel: 'شدة التلعثم الحالية',
    selfSeverityExpectedNextLabel: 'الشدة المتوقعة للمستوى التالي',
    camperdownPerformanceLabel: 'تقييم أدائك',
    clientOpinionLabel: 'رأيك في أدائك',
    submit: 'إرسال العينة',
  },
  sampleRerecord: {
    title: 'إعادة تسجيل الأجزاء المطلوبة',
    instructions: 'أعد تسجيل الأجزاء التالية التي طلب أخصائيك إعادة تسجيلها',
    recorded: 'تم التسجيل',
    submit: 'إرسال',
  },
  reports: {
    title: 'التقارير',
    assessmentResultsTitle: 'نتائج التقييمات',
    medicalReportTitle: 'التقرير الطبي',
    noAssessmentsYet: 'لا توجد تقييمات بعد',
    assessmentTypeLabel: 'النوع',
    assessmentStatusLabel: 'الحالة',
    types: {
      INITIAL: 'أولي',
      PERIODIC: 'دوري',
      FINAL: 'نهائي',
    },
    statuses: {
      DRAFT: 'مسودة',
      APPROVED: 'معتمد',
    },
    severities: {
      MILD: 'خفيف',
      MODERATE: 'متوسط',
      SEVERE: 'شديد',
      VERY_SEVERE: 'شديد جدًا',
    },
    severityLabel: 'شدة التلعثم',
    ssi4TotalLabel: 'مجموع SSI-4',
    approvedAtLabel: 'تاريخ الاعتماد',
    notApprovedYet: 'لم يُعتمد بعد',
    patientNameLabel: 'الاسم',
    referralReasonLabel: 'سبب الإحالة',
    initialDiagnosisLabel: 'التشخيص الأولي',
    medicalHistoryLabel: 'التاريخ الطبي',
    medicationsLabel: 'الأدوية',
    allergiesLabel: 'الحساسية',
    familyHistoryLabel: 'التاريخ العائلي',
    noClinicalInfo: 'لا توجد معلومات سريرية مسجّلة',
    latestAssessmentTitle: 'آخر تقييم معتمد',
    noApprovedAssessment: 'لا يوجد تقييم معتمد بعد',
    activePlanTitle: 'الخطة العلاجية الحالية',
    goalsLabel: 'الأهداف',
    reviewDateLabel: 'تاريخ المراجعة',
    noActivePlan: 'لا توجد خطة علاجية حالية',
    notAvailable: '-',
  },
  complaints: {
    title: 'شكاوى ومقترحاتي',
    submitLinkLabel: 'تقديم شكوى جديدة',
    submitScreenTitle: 'تقديم شكوى أو اقتراح',
    types: {
      COMPLAINT: 'شكوى',
      SUGGESTION: 'اقتراح',
    },
    statuses: {
      OPEN: 'مفتوحة',
      REVIEWED: 'قيد المراجعة',
      RESOLVED: 'تم الحل',
    },
    typeLabel: 'النوع',
    statusLabel: 'الحالة',
    subjectLabel: 'الموضوع',
    descriptionLabel: 'الوصف',
    submitButtonLabel: 'إرسال',
    noComplaintsYet: 'لا توجد شكاوى بعد',
  },
  notifications: {
    title: 'الإشعارات',
    empty: 'لا توجد إشعارات بعد',
  },
  trainingSession: {
    title: 'تدريب اليوم',
    hoursRemainingLabel: 'ساعة متبقية كحد أدنى قبل مرحلة العينة',
    dailyTargetLabel: 'هدف اليوم',
    intervalActiveLabel: 'التدريب التالي متاح الساعة',
    startOrResume: 'ابدأ / استكمل التدريب',
    addUnits: '+10 وحدة',
    unitsProgressLabel: 'وحدة',
    completedTitle: 'أحسنت! أكملت تدريب اليوم',
    backToHome: 'العودة للرئيسية',
    viewLevelContent: 'مشاهدة محتوى المستوى',
    trainingListTitle: 'قائمة التدريب',
  },
};
